### ISSUE TITLE
Code Algorithm

### ISSUE THREAD

**Issue by pnaoum** [loretoparisi/android-mdns-bonjour-discovery#1]
The code works perfectly and discovers services, but if you can write the code algorithm it would be great so it can be further (search for a specific service and get its host IP)

**Comment by zhubinsheng** [comment]
Hello, I found that the service speed was too slow during the test. What do you think

**Comment by loretoparisi** [comment]
@zhubinsheng thanks, not sure, you should look at the mDNS reference implementation to get further info about this in the library I'm using [here](https://github.com/loretoparisi/android-mdns-bonjour-discovery/tree/master/BonjourBrowser/app/src/main/java/javax/jmdns).

Also consider the way how I initialize the service discovery browser [here](https://github.com/loretoparisi/android-mdns-bonjour-discovery/blob/master/BonjourBrowser/app/src/main/java/musixmatch/com/bonjourbrowser/Browser.java#L46)
