### ISSUE TITLE
How the services are being shown? or being inituiated? I mean how services are visible?

### ISSUE THREAD

**Issue by ibrahim-sdsol** [loretoparisi/android-mdns-bonjour-discovery#2]

**Comment by loretoparisi** [comment]
Hello, what do you mean? Services are discovered through mDNS and the initialization is done through service's browser - 

https://github.com/loretoparisi/android-mdns-bonjour-discovery/blob/master/BonjourBrowser/app/src/main/java/musixmatch/com/bonjourbrowser/Browser.java

**Comment by ibrahim-sdsol** [comment]
@loretoparisi where exactly I can see list of devices?

**Comment by loretoparisi** [comment]
As soon as you have a published service around, in the same network, even Bonjour services (it's mDNS based), you should see the list in the main application window. It will work on a simulator too. If not, you will see it in the application logging.

**Comment by metadetron** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @JimmyLee05, @Wu5577, @Hamdyx, @ranqiwei, @seanachao, @Cerebes, @18506711722
